Do not build packages for i386
We're missing a lib:
  Compiling for linux/i386..
  In file included from /usr/include/errno.h:28:0,
                   from god.c:5: /usr/include/features.h:367:25: fatal
                   error: sys/cdefs.h: No such file or directory